version: '3'

volumes:
  ## Kludge for not having the ./docker directory bound recursively
  dockerdirectory:

services:
  wordpress:
    build:
      context: .
      dockerfile: ./docker/wordpress_xdebug/Dockerfile
      args:
        - XDEBUG_REMOTE_PORT=9000 # IDE/Editor's listener port
    container_name: woo_blaze_wordpress
    image: woo_blaze_wordpress
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - '8082:80'
    env_file:
      - default.env
    volumes:
      - ./docker/wordpress:/var/www/html/
      - ./docker/logs/apache2/:/var/log/apache2
      - .:/var/www/html/wp-content/plugins/woo-blaze
      - ./docker/woo-blaze-php.ini:/usr/local/etc/php/conf.d/woo-blaze-php.ini
      - dockerdirectory:/var/www/html/wp-content/plugins/woo-blaze/docker
      - ./docker/bin:/var/scripts
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  db:
    container_name: woo_blaze_mysql
    image: mariadb:10.5.8
    ports:
      - '3308:3306'
    env_file:
      - default.env
    volumes:
      - ./docker/data:/var/lib/mysql
