name: "Create a tag"
description: "Create a tag if the format is correct"

inputs:
  version:
    description: "The version that the action should use to create the tag (e.g. 0.5.0)"
    required: true

outputs:
  trimmed-version:
    description: "The trimmed version"
    value: ${{ steps.version_format_check.outputs.trimmed-version }}
  tag-message:
    description: "The tagging message"
    value: ${{ steps.create_tag.outputs.TAG_MESSAGE }}

runs:
  using: composite
  steps:
    - name: "Check the format of the version"
      id: version_format_check
      uses: ./.github/actions/version-check
      with:
        version: ${{ inputs.version }}

    - name: "Create a tag"
      id: create_tag
      shell: bash
      env:
        VERSION: ${{ steps.version_format_check.outputs.trimmed-version }}
      run: |
        TAG_MESSAGE="Version $VERSION"
        echo ":rocket: Created tag $VERSION. :rocket:" >> $GITHUB_STEP_SUMMARY
        
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git tag -a -m "$TAG_MESSAGE" $VERSION
        git push origin $VERSION
        echo "TAG_MESSAGE=$TAG_MESSAGE" >> $GITHUB_OUTPUT
