name: "Setup Woo Blaze repository"
description: "Handles the setup of the repository (e.g. Node, PNPM, PHP)."

inputs:
  setup-node-pnpm:
    description: "Setup Node and pnpm?"
    required: false
    default: "true"
  setup-php:
    description: "Setup PHP?"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: "Set up pnpm"
      uses: pnpm/action-setup@v2
      if: ${{ inputs.setup-node-pnpm == 'true' }}
      with:
        version: 9
    - name: "Set up Node"
      uses: actions/setup-node@v4
      if: ${{ inputs.setup-node-pnpm == 'true' }}
      with:
        node-version-file: '.nvmrc'
        cache: "pnpm"

    - name: "Enable composer dependencies caching"
      uses: actions/cache@v3
      if: ${{ inputs.setup-php == 'true' }}
      with:
        path: ~/.cache/composer/
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

    - name: "Set up PHP"
      uses: ./.github/actions/setup-php
      if: ${{ inputs.setup-php == 'true' }}
