name: "Check the format of a version"
description: "Checks the format of a version"

inputs:
  version:
    description: "The version that the action should check (e.g. 0.5.0)"
    required: true

outputs:
  trimmed-version:
    description: "The trimmed version"
    value: ${{ steps.version_format_check.outputs.VERSION }}

runs:
  using: composite
  steps:
    - name: "Check the format of the version"
      id: version_format_check
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        # Trim leading and ending whitespaces
        TRIMMED_VERSION=$(echo "$VERSION" | xargs) 

        VERSION_FORMAT="^[0-9]+\.[0-9]\.[0-9]+$"

        if [[ $TRIMMED_VERSION =~ $VERSION_FORMAT ]]; then
          echo "VERSION=$TRIMMED_VERSION" >> $GITHUB_OUTPUT
        else
          echo "::error::The version provided doesn't respect the format expected (version: $TRIMMED_VERSION; format: $VERSION_FORMAT)."
          exit 1
        fi
