name: Linting and testing

on:
  pull_request:
  merge_group:

env:
  WP_VERSION: latest
  WC_VERSION: '7.6.0'

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      # clone the repository
      - uses: actions/checkout@v4
      - name: "Set up Repository (Node, pnpm and PHP)"
        uses: ./.github/actions/setup-repo
      # install dependencies and run linter
      - run: pnpm install && pnpm lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      # clone the repository
      - uses: actions/checkout@v4
      - name: "Set up Repository (PHP only)"
        uses: ./.github/actions/setup-repo
        with:
          setup-node-pnpm: "false"
      # run tests
      - run: bash bin/run-ci-tests.sh
